# Copyright © 2026 Cisco Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sysrepo
import signal
import xml.etree.ElementTree as ET
import os
# import json
# import sys
# from datetime import datetime

# Define the RPC path you want to mock
RPC_XPATH = "/Cisco-IOS-XE-rpc:app-hosting"
OPER_XPATH = "Cisco-IOS-XE-app-hosting-oper:app-hosting-oper-data"
OPER_FILE = "/yang-modules/operational/app_hosting_oper.xml"
# Namespaces and Modules
CFG_MODULE = "Cisco-IOS-XE-app-hosting-cfg"
OPER_MODULE = "Cisco-IOS-XE-app-hosting-oper"

def app_hosting_callback(xpath, input_params, event, private_data):
    """
    This function handles the RPC request.
    input_params: Dictionary of input data sent by the RESTCONF client.
    """
    print(f"Received RPC call: {xpath}")
    print(f"Input parameters: {input_params}")

    appid = None
    target_state = 'UNKNOWN'
    if (data := input_params.get('install')):
        appid = data.get('appid')
        target_state = 'DEPLOYED'
    elif (data := input_params.get('activate')):
        appid = data.get('appid')
        target_state = 'ACTIVATED'
    elif (data := input_params.get('start')):
        appid = data.get('appid')
        target_state = 'RUNNING'
    elif (data := input_params.get('stop')):
        appid = data.get('appid')
        target_state = 'STOPPED'
    elif (data := input_params.get('deactivate')):
        appid = data.get('appid')
        target_state = 'INACTIVE'
    elif (data := input_params.get('uninstall')):
        appid = data.get('appid')
        target_state = 'UNKNOWN'
    else:
        print("Error: Unknown RPC payload.")
        return {"result": "error", "detail": "Missing application identifier."}

    print(f"Processing request for app: {appid}")
    # update_app_status(appid, target_state, private_data)
    update_xml_file_directly(appid, target_state, OPER_FILE)
    # MOCK LOGIC: Simulate different behaviors based on input
    # For example, if app-id is 'test-app', return success.
    # Adjust key names based on the actual YANG model structure.
    
    # Return an output dictionary matching the YANG 'output' definition
    # If the RPC has no output, return None or an empty dict.
    return {"result": "success", "detail": "App-hosting stub executed successfully."}


def update_app_status(app_name, new_status, private_data):

    base_xpath = f"/Cisco-IOS-XE-app-hosting-oper:app-hosting-oper-data/app[name='{app_name}']"
    try:
        # Push the data to the operational datastore
        private_data['sess'].set_item(f"{base_xpath}/details/state", new_status)
        private_data['sess'].apply_changes()
        
        print(f"[+] Successfully pushed {new_status} to operational datastore.")
        return {"result": "success"}
    except Exception as e:
        print(f"[-] Push failed: {e}")
        return {"result": "error", "detail": str(e)}


def update_xml_file_directly(app_name, new_status, file_path):
    OPER_NS = "cisco.com"
    
    # 1. GLOBAL REGISTRATION (Critical for removing ns0)
    # Registering empty string "" forces this URI to be the default (no prefix)
    ET.register_namespace('', OPER_NS)
    # Registering the second one prevents it from being autogenerated as ns1
    ET.register_namespace('app-hosting-ios-xe-oper', OPER_NS)

    if not os.path.exists(file_path) or os.path.getsize(file_path) == 0:
        print(f"[!] Error: File {file_path} is missing or empty.")
        return False

    try:
        tree = ET.parse(file_path)
        root = tree.getroot()

        # 2. Wildcard search handles any existing prefix issues during lookup
        xpath_query = f".//{{*}}app[{{*}}name='{app_name}']/{{*}}details/{{*}}state"
        state_node = root.find(xpath_query)

        if state_node is not None:
            state_node.text = new_status
            
            # 3. MANUALLY SET the root attributes to match your exact required header
            # This ensures both declarations appear in the first tag
            root.set("xmlns", OPER_NS)
            root.set("xmlns:app-hosting-ios-xe-oper", OPER_NS)

            # 4. PRETTY PRINT (Standard in 2025 Python 3.9+)
            ET.indent(root, space="  ")
            
            # 5. WRITE WITHOUT default_namespace
            # Passing default_namespace into write() often causes the "non-qualified names" 
            # error when manual xmlns attributes are present. 
            # Rely on the global register_namespace above instead.
            tree.write(file_path, encoding="utf-8", xml_declaration=False)
            
            print(f"[+] Successfully updated {app_name} to {new_status} with clean XML.")
            return True
        else:
            print(f"[!] App '{app_name}' not found.")
            return False

    except Exception as e:
        print(f"[-] Error: {e}")
        return False


def main():
    try:
        with sysrepo.SysrepoConnection() as conn:
            # IMPORTANT: We open the sessions and keep them open in the 'with' scope.
            # This ensures operational data doesn't vanish.
            with conn.start_session("operational") as sess_oper:
                with conn.start_session("running") as sess_rpc:
                    
                    # Create the dictionary that will be passed to the callback
                    # Ensure keys here match the keys used in update_app_status
                    priv_data = {
                        'sess': sess_oper
                    }
                    
                    print(f"[*] Subscribing to /Cisco-IOS-XE-rpc:app-hosting...")
                    sess_rpc.subscribe_rpc_call(
                        "/Cisco-IOS-XE-rpc:app-hosting", 
                        app_hosting_callback, 
                        private_data=priv_data
                    )
                    
                    print("[*] Stub is active. Press Ctrl+C to stop.")
                    # signal.pause() is used to keep the script (and sessions) alive
                    signal.pause()
                    
    except KeyboardInterrupt:
        print("\n[*] Exiting...")
    except Exception as e:
        print(f"[-] Fatal Error: {e}")


if __name__ == "__main__":
    main()
