//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyLogEntry) DeepCopyInto(out *ApplyLogEntry) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.Families != nil {
		in, out := &in.Families, &out.Families
		*out = make([]FamilyApplyOutcome, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyLogEntry.
func (in *ApplyLogEntry) DeepCopy() *ApplyLogEntry {
	if in == nil {
		return nil
	}
	out := new(ApplyLogEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapturedConfigMapRef) DeepCopyInto(out *CapturedConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapturedConfigMapRef.
func (in *CapturedConfigMapRef) DeepCopy() *CapturedConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(CapturedConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardinalityLimits) DeepCopyInto(out *CardinalityLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardinalityLimits.
func (in *CardinalityLimits) DeepCopy() *CardinalityLimits {
	if in == nil {
		return nil
	}
	out := new(CardinalityLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandOutput) DeepCopyInto(out *CommandOutput) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(CapturedConfigMapRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandOutput.
func (in *CommandOutput) DeepCopy() *CommandOutput {
	if in == nil {
		return nil
	}
	out := new(CommandOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSource) DeepCopyInto(out *ConfigurationSource) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSource.
func (in *ConfigurationSource) DeepCopy() *ConfigurationSource {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceRef) DeepCopyInto(out *DeviceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceRef.
func (in *DeviceRef) DeepCopy() *DeviceRef {
	if in == nil {
		return nil
	}
	out := new(DeviceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticCapture) DeepCopyInto(out *DiagnosticCapture) {
	*out = *in
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]CommandOutput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticCapture.
func (in *DiagnosticCapture) DeepCopy() *DiagnosticCapture {
	if in == nil {
		return nil
	}
	out := new(DiagnosticCapture)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticConfigMapSink) DeepCopyInto(out *DiagnosticConfigMapSink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticConfigMapSink.
func (in *DiagnosticConfigMapSink) DeepCopy() *DiagnosticConfigMapSink {
	if in == nil {
		return nil
	}
	out := new(DiagnosticConfigMapSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticOutputSink) DeepCopyInto(out *DiagnosticOutputSink) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(DiagnosticConfigMapSink)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticOutputSink.
func (in *DiagnosticOutputSink) DeepCopy() *DiagnosticOutputSink {
	if in == nil {
		return nil
	}
	out := new(DiagnosticOutputSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticRetention) DeepCopyInto(out *DiagnosticRetention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticRetention.
func (in *DiagnosticRetention) DeepCopy() *DiagnosticRetention {
	if in == nil {
		return nil
	}
	out := new(DiagnosticRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticSchedule) DeepCopyInto(out *DiagnosticSchedule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticSchedule.
func (in *DiagnosticSchedule) DeepCopy() *DiagnosticSchedule {
	if in == nil {
		return nil
	}
	out := new(DiagnosticSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftEntry) DeepCopyInto(out *DriftEntry) {
	*out = *in
	in.Detected.DeepCopyInto(&out.Detected)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftEntry.
func (in *DriftEntry) DeepCopy() *DriftEntry {
	if in == nil {
		return nil
	}
	out := new(DriftEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FamilyApplyOutcome) DeepCopyInto(out *FamilyApplyOutcome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FamilyApplyOutcome.
func (in *FamilyApplyOutcome) DeepCopy() *FamilyApplyOutcome {
	if in == nil {
		return nil
	}
	out := new(FamilyApplyOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FamilySecretRef) DeepCopyInto(out *FamilySecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FamilySecretRef.
func (in *FamilySecretRef) DeepCopy() *FamilySecretRef {
	if in == nil {
		return nil
	}
	out := new(FamilySecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FamilyStatus) DeepCopyInto(out *FamilyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FamilyStatus.
func (in *FamilyStatus) DeepCopy() *FamilyStatus {
	if in == nil {
		return nil
	}
	out := new(FamilyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterConfig) DeepCopyInto(out *FilterConfig) {
	*out = *in
	if in.WirePath != nil {
		in, out := &in.WirePath, &out.WirePath
		*out = new(FilterRules)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(FilterRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterConfig.
func (in *FilterConfig) DeepCopy() *FilterConfig {
	if in == nil {
		return nil
	}
	out := new(FilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterRules) DeepCopyInto(out *FilterRules) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterRules.
func (in *FilterRules) DeepCopy() *FilterRules {
	if in == nil {
		return nil
	}
	out := new(FilterRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedCR) DeepCopyInto(out *GeneratedCR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedCR.
func (in *GeneratedCR) DeepCopy() *GeneratedCR {
	if in == nil {
		return nil
	}
	out := new(GeneratedCR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfig) DeepCopyInto(out *IOSXEConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfig.
func (in *IOSXEConfig) DeepCopy() *IOSXEConfig {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigApplyLog) DeepCopyInto(out *IOSXEConfigApplyLog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigApplyLog.
func (in *IOSXEConfigApplyLog) DeepCopy() *IOSXEConfigApplyLog {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigApplyLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEConfigApplyLog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigApplyLogList) DeepCopyInto(out *IOSXEConfigApplyLogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXEConfigApplyLog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigApplyLogList.
func (in *IOSXEConfigApplyLogList) DeepCopy() *IOSXEConfigApplyLogList {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigApplyLogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEConfigApplyLogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigApplyLogSpec) DeepCopyInto(out *IOSXEConfigApplyLogSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigApplyLogSpec.
func (in *IOSXEConfigApplyLogSpec) DeepCopy() *IOSXEConfigApplyLogSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigApplyLogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigApplyLogStatus) DeepCopyInto(out *IOSXEConfigApplyLogStatus) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]ApplyLogEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OldestRetainedAt != nil {
		in, out := &in.OldestRetainedAt, &out.OldestRetainedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigApplyLogStatus.
func (in *IOSXEConfigApplyLogStatus) DeepCopy() *IOSXEConfigApplyLogStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigApplyLogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigBundle) DeepCopyInto(out *IOSXEConfigBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigBundle.
func (in *IOSXEConfigBundle) DeepCopy() *IOSXEConfigBundle {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEConfigBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigBundleList) DeepCopyInto(out *IOSXEConfigBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXEConfigBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigBundleList.
func (in *IOSXEConfigBundleList) DeepCopy() *IOSXEConfigBundleList {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEConfigBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigBundleSpec) DeepCopyInto(out *IOSXEConfigBundleSpec) {
	*out = *in
	if in.DeviceRefs != nil {
		in, out := &in.DeviceRefs, &out.DeviceRefs
		*out = make([]DeviceRef, len(*in))
		copy(*out, *in)
	}
	if in.DeviceSelector != nil {
		in, out := &in.DeviceSelector, &out.DeviceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigBundleSpec.
func (in *IOSXEConfigBundleSpec) DeepCopy() *IOSXEConfigBundleSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigBundleStatus) DeepCopyInto(out *IOSXEConfigBundleStatus) {
	*out = *in
	if in.GeneratedCRs != nil {
		in, out := &in.GeneratedCRs, &out.GeneratedCRs
		*out = make([]GeneratedCR, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigBundleStatus.
func (in *IOSXEConfigBundleStatus) DeepCopy() *IOSXEConfigBundleStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigDefaults) DeepCopyInto(out *IOSXEConfigDefaults) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigDefaults.
func (in *IOSXEConfigDefaults) DeepCopy() *IOSXEConfigDefaults {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEConfigDefaults) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigDefaultsList) DeepCopyInto(out *IOSXEConfigDefaultsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXEConfigDefaults, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigDefaultsList.
func (in *IOSXEConfigDefaultsList) DeepCopy() *IOSXEConfigDefaultsList {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigDefaultsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEConfigDefaultsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigDefaultsSpec) DeepCopyInto(out *IOSXEConfigDefaultsSpec) {
	*out = *in
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigDefaultsSpec.
func (in *IOSXEConfigDefaultsSpec) DeepCopy() *IOSXEConfigDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigDefaultsStatus) DeepCopyInto(out *IOSXEConfigDefaultsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigDefaultsStatus.
func (in *IOSXEConfigDefaultsStatus) DeepCopy() *IOSXEConfigDefaultsStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigDefaultsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigList) DeepCopyInto(out *IOSXEConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXEConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigList.
func (in *IOSXEConfigList) DeepCopy() *IOSXEConfigList {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigSpec) DeepCopyInto(out *IOSXEConfigSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	in.IOSXEConfigTemplateSpec.DeepCopyInto(&out.IOSXEConfigTemplateSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigSpec.
func (in *IOSXEConfigSpec) DeepCopy() *IOSXEConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigStatus) DeepCopyInto(out *IOSXEConfigStatus) {
	*out = *in
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
	if in.LastDeviceCheck != nil {
		in, out := &in.LastDeviceCheck, &out.LastDeviceCheck
		*out = (*in).DeepCopy()
	}
	if in.FamilyStatus != nil {
		in, out := &in.FamilyStatus, &out.FamilyStatus
		*out = make([]FamilyStatus, len(*in))
		copy(*out, *in)
	}
	if in.Drift != nil {
		in, out := &in.Drift, &out.Drift
		*out = make([]DriftEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AtomicReplaceOwnedKeys != nil {
		in, out := &in.AtomicReplaceOwnedKeys, &out.AtomicReplaceOwnedKeys
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigStatus.
func (in *IOSXEConfigStatus) DeepCopy() *IOSXEConfigStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEConfigTemplateSpec) DeepCopyInto(out *IOSXEConfigTemplateSpec) {
	*out = *in
	if in.DeviceGroups != nil {
		in, out := &in.DeviceGroups, &out.DeviceGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InterfaceGroups != nil {
		in, out := &in.InterfaceGroups, &out.InterfaceGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TemplateRefs != nil {
		in, out := &in.TemplateRefs, &out.TemplateRefs
		*out = make([]TemplateRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedFamilies != nil {
		in, out := &in.ManagedFamilies, &out.ManagedFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Source.DeepCopyInto(&out.Source)
	if in.SecretRefs != nil {
		in, out := &in.SecretRefs, &out.SecretRefs
		*out = make([]FamilySecretRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEConfigTemplateSpec.
func (in *IOSXEConfigTemplateSpec) DeepCopy() *IOSXEConfigTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEConfigTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEDeviceGroupConfig) DeepCopyInto(out *IOSXEDeviceGroupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEDeviceGroupConfig.
func (in *IOSXEDeviceGroupConfig) DeepCopy() *IOSXEDeviceGroupConfig {
	if in == nil {
		return nil
	}
	out := new(IOSXEDeviceGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEDeviceGroupConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEDeviceGroupConfigList) DeepCopyInto(out *IOSXEDeviceGroupConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXEDeviceGroupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEDeviceGroupConfigList.
func (in *IOSXEDeviceGroupConfigList) DeepCopy() *IOSXEDeviceGroupConfigList {
	if in == nil {
		return nil
	}
	out := new(IOSXEDeviceGroupConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEDeviceGroupConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEDeviceGroupConfigSpec) DeepCopyInto(out *IOSXEDeviceGroupConfigSpec) {
	*out = *in
	if in.DeviceRefs != nil {
		in, out := &in.DeviceRefs, &out.DeviceRefs
		*out = make([]DeviceRef, len(*in))
		copy(*out, *in)
	}
	if in.DeviceSelector != nil {
		in, out := &in.DeviceSelector, &out.DeviceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEDeviceGroupConfigSpec.
func (in *IOSXEDeviceGroupConfigSpec) DeepCopy() *IOSXEDeviceGroupConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEDeviceGroupConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEDeviceGroupConfigStatus) DeepCopyInto(out *IOSXEDeviceGroupConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEDeviceGroupConfigStatus.
func (in *IOSXEDeviceGroupConfigStatus) DeepCopy() *IOSXEDeviceGroupConfigStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXEDeviceGroupConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEDiagnostic) DeepCopyInto(out *IOSXEDiagnostic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEDiagnostic.
func (in *IOSXEDiagnostic) DeepCopy() *IOSXEDiagnostic {
	if in == nil {
		return nil
	}
	out := new(IOSXEDiagnostic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEDiagnostic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEDiagnosticList) DeepCopyInto(out *IOSXEDiagnosticList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXEDiagnostic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEDiagnosticList.
func (in *IOSXEDiagnosticList) DeepCopy() *IOSXEDiagnosticList {
	if in == nil {
		return nil
	}
	out := new(IOSXEDiagnosticList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEDiagnosticList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEDiagnosticSpec) DeepCopyInto(out *IOSXEDiagnosticSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(DiagnosticSchedule)
		**out = **in
	}
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(DiagnosticRetention)
		**out = **in
	}
	if in.OutputSink != nil {
		in, out := &in.OutputSink, &out.OutputSink
		*out = new(DiagnosticOutputSink)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEDiagnosticSpec.
func (in *IOSXEDiagnosticSpec) DeepCopy() *IOSXEDiagnosticSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEDiagnosticSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEDiagnosticStatus) DeepCopyInto(out *IOSXEDiagnosticStatus) {
	*out = *in
	if in.LastCapture != nil {
		in, out := &in.LastCapture, &out.LastCapture
		*out = (*in).DeepCopy()
	}
	if in.NextCapture != nil {
		in, out := &in.NextCapture, &out.NextCapture
		*out = (*in).DeepCopy()
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]DiagnosticCapture, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEDiagnosticStatus.
func (in *IOSXEDiagnosticStatus) DeepCopy() *IOSXEDiagnosticStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXEDiagnosticStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEInterfaceGroupConfig) DeepCopyInto(out *IOSXEInterfaceGroupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEInterfaceGroupConfig.
func (in *IOSXEInterfaceGroupConfig) DeepCopy() *IOSXEInterfaceGroupConfig {
	if in == nil {
		return nil
	}
	out := new(IOSXEInterfaceGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEInterfaceGroupConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEInterfaceGroupConfigList) DeepCopyInto(out *IOSXEInterfaceGroupConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXEInterfaceGroupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEInterfaceGroupConfigList.
func (in *IOSXEInterfaceGroupConfigList) DeepCopy() *IOSXEInterfaceGroupConfigList {
	if in == nil {
		return nil
	}
	out := new(IOSXEInterfaceGroupConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEInterfaceGroupConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEInterfaceGroupConfigSpec) DeepCopyInto(out *IOSXEInterfaceGroupConfigSpec) {
	*out = *in
	if in.DeviceRefs != nil {
		in, out := &in.DeviceRefs, &out.DeviceRefs
		*out = make([]DeviceRef, len(*in))
		copy(*out, *in)
	}
	if in.DeviceSelector != nil {
		in, out := &in.DeviceSelector, &out.DeviceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.InterfaceSelector != nil {
		in, out := &in.InterfaceSelector, &out.InterfaceSelector
		*out = make([]InterfaceMatch, len(*in))
		copy(*out, *in)
	}
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEInterfaceGroupConfigSpec.
func (in *IOSXEInterfaceGroupConfigSpec) DeepCopy() *IOSXEInterfaceGroupConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEInterfaceGroupConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEInterfaceGroupConfigStatus) DeepCopyInto(out *IOSXEInterfaceGroupConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEInterfaceGroupConfigStatus.
func (in *IOSXEInterfaceGroupConfigStatus) DeepCopy() *IOSXEInterfaceGroupConfigStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXEInterfaceGroupConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXETelemetry) DeepCopyInto(out *IOSXETelemetry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXETelemetry.
func (in *IOSXETelemetry) DeepCopy() *IOSXETelemetry {
	if in == nil {
		return nil
	}
	out := new(IOSXETelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXETelemetry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXETelemetryList) DeepCopyInto(out *IOSXETelemetryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXETelemetry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXETelemetryList.
func (in *IOSXETelemetryList) DeepCopy() *IOSXETelemetryList {
	if in == nil {
		return nil
	}
	out := new(IOSXETelemetryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXETelemetryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXETelemetrySpec) DeepCopyInto(out *IOSXETelemetrySpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	if in.Subscriptions != nil {
		in, out := &in.Subscriptions, &out.Subscriptions
		*out = make([]TelemetrySubscription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reconnect != nil {
		in, out := &in.Reconnect, &out.Reconnect
		*out = new(ReconnectConfig)
		**out = **in
	}
	if in.CardinalityLimits != nil {
		in, out := &in.CardinalityLimits, &out.CardinalityLimits
		*out = new(CardinalityLimits)
		**out = **in
	}
	if in.Timestamps != nil {
		in, out := &in.Timestamps, &out.Timestamps
		*out = new(TimestampConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = new(MappingConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Output.DeepCopyInto(&out.Output)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXETelemetrySpec.
func (in *IOSXETelemetrySpec) DeepCopy() *IOSXETelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(IOSXETelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXETelemetryStatus) DeepCopyInto(out *IOSXETelemetryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedSubscriptionState != nil {
		in, out := &in.ObservedSubscriptionState, &out.ObservedSubscriptionState
		*out = make([]ObservedSubscriptionState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXETelemetryStatus.
func (in *IOSXETelemetryStatus) DeepCopy() *IOSXETelemetryStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXETelemetryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXETemplate) DeepCopyInto(out *IOSXETemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXETemplate.
func (in *IOSXETemplate) DeepCopy() *IOSXETemplate {
	if in == nil {
		return nil
	}
	out := new(IOSXETemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXETemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXETemplateList) DeepCopyInto(out *IOSXETemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXETemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXETemplateList.
func (in *IOSXETemplateList) DeepCopy() *IOSXETemplateList {
	if in == nil {
		return nil
	}
	out := new(IOSXETemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXETemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXETemplateSpec) DeepCopyInto(out *IOSXETemplateSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]TemplateParameter, len(*in))
		copy(*out, *in)
	}
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXETemplateSpec.
func (in *IOSXETemplateSpec) DeepCopy() *IOSXETemplateSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXETemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXETemplateStatus) DeepCopyInto(out *IOSXETemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXETemplateStatus.
func (in *IOSXETemplateStatus) DeepCopy() *IOSXETemplateStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXETemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceMatch) DeepCopyInto(out *InterfaceMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceMatch.
func (in *InterfaceMatch) DeepCopy() *InterfaceMatch {
	if in == nil {
		return nil
	}
	out := new(InterfaceMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingConfig) DeepCopyInto(out *MappingConfig) {
	*out = *in
	if in.PathAliases != nil {
		in, out := &in.PathAliases, &out.PathAliases
		*out = make([]PathAlias, len(*in))
		copy(*out, *in)
	}
	if in.MetricTypeOverrides != nil {
		in, out := &in.MetricTypeOverrides, &out.MetricTypeOverrides
		*out = make([]MetricTypeOverride, len(*in))
		copy(*out, *in)
	}
	if in.Transitions != nil {
		in, out := &in.Transitions, &out.Transitions
		*out = make([]Transition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceAttributes != nil {
		in, out := &in.ResourceAttributes, &out.ResourceAttributes
		*out = make([]ResourceAttribute, len(*in))
		copy(*out, *in)
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(FilterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingConfig.
func (in *MappingConfig) DeepCopy() *MappingConfig {
	if in == nil {
		return nil
	}
	out := new(MappingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricTypeOverride) DeepCopyInto(out *MetricTypeOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricTypeOverride.
func (in *MetricTypeOverride) DeepCopy() *MetricTypeOverride {
	if in == nil {
		return nil
	}
	out := new(MetricTypeOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedSubscriptionState) DeepCopyInto(out *ObservedSubscriptionState) {
	*out = *in
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
	if in.DroppedEvents != nil {
		in, out := &in.DroppedEvents, &out.DroppedEvents
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.CurrentBackoff = in.CurrentBackoff
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedSubscriptionState.
func (in *ObservedSubscriptionState) DeepCopy() *ObservedSubscriptionState {
	if in == nil {
		return nil
	}
	out := new(ObservedSubscriptionState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputConfig) DeepCopyInto(out *OutputConfig) {
	*out = *in
	if in.Signal != nil {
		in, out := &in.Signal, &out.Signal
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputConfig.
func (in *OutputConfig) DeepCopy() *OutputConfig {
	if in == nil {
		return nil
	}
	out := new(OutputConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathAlias) DeepCopyInto(out *PathAlias) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathAlias.
func (in *PathAlias) DeepCopy() *PathAlias {
	if in == nil {
		return nil
	}
	out := new(PathAlias)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconnectConfig) DeepCopyInto(out *ReconnectConfig) {
	*out = *in
	out.InitialBackoff = in.InitialBackoff
	out.MaxBackoff = in.MaxBackoff
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconnectConfig.
func (in *ReconnectConfig) DeepCopy() *ReconnectConfig {
	if in == nil {
		return nil
	}
	out := new(ReconnectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceAttribute) DeepCopyInto(out *ResourceAttribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceAttribute.
func (in *ResourceAttribute) DeepCopy() *ResourceAttribute {
	if in == nil {
		return nil
	}
	out := new(ResourceAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySubscription) DeepCopyInto(out *TelemetrySubscription) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PreservePathPrefix != nil {
		in, out := &in.PreservePathPrefix, &out.PreservePathPrefix
		*out = new(bool)
		**out = **in
	}
	out.SampleInterval = in.SampleInterval
	if in.HeartbeatInterval != nil {
		in, out := &in.HeartbeatInterval, &out.HeartbeatInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SuppressRedundant != nil {
		in, out := &in.SuppressRedundant, &out.SuppressRedundant
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySubscription.
func (in *TelemetrySubscription) DeepCopy() *TelemetrySubscription {
	if in == nil {
		return nil
	}
	out := new(TelemetrySubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateParameter) DeepCopyInto(out *TemplateParameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateParameter.
func (in *TemplateParameter) DeepCopy() *TemplateParameter {
	if in == nil {
		return nil
	}
	out := new(TemplateParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateRef) DeepCopyInto(out *TemplateRef) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateRef.
func (in *TemplateRef) DeepCopy() *TemplateRef {
	if in == nil {
		return nil
	}
	out := new(TemplateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampConfig) DeepCopyInto(out *TimestampConfig) {
	*out = *in
	if in.UseCollectorTimestamp != nil {
		in, out := &in.UseCollectorTimestamp, &out.UseCollectorTimestamp
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampConfig.
func (in *TimestampConfig) DeepCopy() *TimestampConfig {
	if in == nil {
		return nil
	}
	out := new(TimestampConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transition) DeepCopyInto(out *Transition) {
	*out = *in
	if in.HealthyValues != nil {
		in, out := &in.HealthyValues, &out.HealthyValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UnhealthyValues != nil {
		in, out := &in.UnhealthyValues, &out.UnhealthyValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transition.
func (in *Transition) DeepCopy() *Transition {
	if in == nil {
		return nil
	}
	out := new(Transition)
	in.DeepCopyInto(out)
	return out
}
