---
apiVersion: v1
kind: Pod
metadata:
  name: nginxonswitch
spec:
  nodeSelector:
    kubernetes.io/hostname: cvk-dev-node
  containers:
  - name: nginx
    image: flash:/nginx.tar
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-on-switch2
# spec:
#   nodeSelector:
#     kubernetes.io/hostname: cheekycheek
#   containers:
#   - name: nginx
#     image: flash:/nginx.tar
#     resources:
#       requests:
#         cpu: "500m"
#         memory: "256Mi"
