---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-on-switch
spec:
  nodeSelector:
    kubernetes.io/hostname: cvk-dev-node
  containers:
  - name: nginx
    image: flash:/nginx.tar
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
  # - name: donkey
  #   image: flash:/nginx.tar
  #   resources:
  #     requests:
  #       cpu: "500m"
  #       memory: "256Mi"
