apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ciscodevice.yaml
  - iosxeconfig.yaml
configMapGenerator:
  - name: edge-01-data
    files:
      - data.nac.yaml=data.nac.yaml
generatorOptions:
  disableNameSuffixHash: true
