//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRequest) DeepCopyInto(out *ActionRequest) {
	*out = *in
	if in.Reboot != nil {
		in, out := &in.Reboot, &out.Reboot
		*out = new(RebootActionArgs)
		**out = **in
	}
	if in.CancelReboot != nil {
		in, out := &in.CancelReboot, &out.CancelReboot
		*out = new(CancelRebootArgs)
		**out = **in
	}
	if in.KillProcess != nil {
		in, out := &in.KillProcess, &out.KillProcess
		*out = new(KillProcessArgs)
		**out = **in
	}
	if in.FilePut != nil {
		in, out := &in.FilePut, &out.FilePut
		*out = new(FilePutArgs)
		**out = **in
	}
	if in.FileRemove != nil {
		in, out := &in.FileRemove, &out.FileRemove
		*out = new(FileRemoveArgs)
		**out = **in
	}
	if in.FactoryReset != nil {
		in, out := &in.FactoryReset, &out.FactoryReset
		*out = new(FactoryResetArgs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRequest.
func (in *ActionRequest) DeepCopy() *ActionRequest {
	if in == nil {
		return nil
	}
	out := new(ActionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CancelRebootArgs) DeepCopyInto(out *CancelRebootArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CancelRebootArgs.
func (in *CancelRebootArgs) DeepCopy() *CancelRebootArgs {
	if in == nil {
		return nil
	}
	out := new(CancelRebootArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceOperation) DeepCopyInto(out *DeviceOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceOperation.
func (in *DeviceOperation) DeepCopy() *DeviceOperation {
	if in == nil {
		return nil
	}
	out := new(DeviceOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceOperationList) DeepCopyInto(out *DeviceOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeviceOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceOperationList.
func (in *DeviceOperationList) DeepCopy() *DeviceOperationList {
	if in == nil {
		return nil
	}
	out := new(DeviceOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceOperationOutput) DeepCopyInto(out *DeviceOperationOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceOperationOutput.
func (in *DeviceOperationOutput) DeepCopy() *DeviceOperationOutput {
	if in == nil {
		return nil
	}
	out := new(DeviceOperationOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceOperationRequest) DeepCopyInto(out *DeviceOperationRequest) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GNOI != nil {
		in, out := &in.GNOI, &out.GNOI
		*out = new(GNOIArgs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceOperationRequest.
func (in *DeviceOperationRequest) DeepCopy() *DeviceOperationRequest {
	if in == nil {
		return nil
	}
	out := new(DeviceOperationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceOperationSpec) DeepCopyInto(out *DeviceOperationSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	in.Operation.DeepCopyInto(&out.Operation)
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceOperationSpec.
func (in *DeviceOperationSpec) DeepCopy() *DeviceOperationSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceOperationStatus) DeepCopyInto(out *DeviceOperationStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ArtifactURIs != nil {
		in, out := &in.ArtifactURIs, &out.ArtifactURIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]DeviceOperationOutput, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceOperationStatus.
func (in *DeviceOperationStatus) DeepCopy() *DeviceOperationStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FactoryResetArgs) DeepCopyInto(out *FactoryResetArgs) {
	*out = *in
	if in.RetainCerts != nil {
		in, out := &in.RetainCerts, &out.RetainCerts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FactoryResetArgs.
func (in *FactoryResetArgs) DeepCopy() *FactoryResetArgs {
	if in == nil {
		return nil
	}
	out := new(FactoryResetArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilePutArgs) DeepCopyInto(out *FilePutArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilePutArgs.
func (in *FilePutArgs) DeepCopy() *FilePutArgs {
	if in == nil {
		return nil
	}
	out := new(FilePutArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRemoveArgs) DeepCopyInto(out *FileRemoveArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRemoveArgs.
func (in *FileRemoveArgs) DeepCopy() *FileRemoveArgs {
	if in == nil {
		return nil
	}
	out := new(FileRemoveArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOIArgs) DeepCopyInto(out *GNOIArgs) {
	*out = *in
	if in.Ping != nil {
		in, out := &in.Ping, &out.Ping
		*out = new(GNOIPingArgs)
		**out = **in
	}
	if in.Traceroute != nil {
		in, out := &in.Traceroute, &out.Traceroute
		*out = new(GNOITracerouteArgs)
		**out = **in
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(GNOIFileArgs)
		**out = **in
	}
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(GNOICertArgs)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOIArgs.
func (in *GNOIArgs) DeepCopy() *GNOIArgs {
	if in == nil {
		return nil
	}
	out := new(GNOIArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOICertArgs) DeepCopyInto(out *GNOICertArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOICertArgs.
func (in *GNOICertArgs) DeepCopy() *GNOICertArgs {
	if in == nil {
		return nil
	}
	out := new(GNOICertArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOIFileArgs) DeepCopyInto(out *GNOIFileArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOIFileArgs.
func (in *GNOIFileArgs) DeepCopy() *GNOIFileArgs {
	if in == nil {
		return nil
	}
	out := new(GNOIFileArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOIPingArgs) DeepCopyInto(out *GNOIPingArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOIPingArgs.
func (in *GNOIPingArgs) DeepCopy() *GNOIPingArgs {
	if in == nil {
		return nil
	}
	out := new(GNOIPingArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOITracerouteArgs) DeepCopyInto(out *GNOITracerouteArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOITracerouteArgs.
func (in *GNOITracerouteArgs) DeepCopy() *GNOITracerouteArgs {
	if in == nil {
		return nil
	}
	out := new(GNOITracerouteArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEOperationalAction) DeepCopyInto(out *IOSXEOperationalAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEOperationalAction.
func (in *IOSXEOperationalAction) DeepCopy() *IOSXEOperationalAction {
	if in == nil {
		return nil
	}
	out := new(IOSXEOperationalAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEOperationalAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEOperationalActionList) DeepCopyInto(out *IOSXEOperationalActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXEOperationalAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEOperationalActionList.
func (in *IOSXEOperationalActionList) DeepCopy() *IOSXEOperationalActionList {
	if in == nil {
		return nil
	}
	out := new(IOSXEOperationalActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXEOperationalActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEOperationalActionSpec) DeepCopyInto(out *IOSXEOperationalActionSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	in.Action.DeepCopyInto(&out.Action)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEOperationalActionSpec.
func (in *IOSXEOperationalActionSpec) DeepCopy() *IOSXEOperationalActionSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXEOperationalActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXEOperationalActionStatus) DeepCopyInto(out *IOSXEOperationalActionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXEOperationalActionStatus.
func (in *IOSXEOperationalActionStatus) DeepCopy() *IOSXEOperationalActionStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXEOperationalActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXESoftwareUpgrade) DeepCopyInto(out *IOSXESoftwareUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXESoftwareUpgrade.
func (in *IOSXESoftwareUpgrade) DeepCopy() *IOSXESoftwareUpgrade {
	if in == nil {
		return nil
	}
	out := new(IOSXESoftwareUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXESoftwareUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXESoftwareUpgradeList) DeepCopyInto(out *IOSXESoftwareUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IOSXESoftwareUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXESoftwareUpgradeList.
func (in *IOSXESoftwareUpgradeList) DeepCopy() *IOSXESoftwareUpgradeList {
	if in == nil {
		return nil
	}
	out := new(IOSXESoftwareUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IOSXESoftwareUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXESoftwareUpgradeSpec) DeepCopyInto(out *IOSXESoftwareUpgradeSpec) {
	*out = *in
	out.DeviceRef = in.DeviceRef
	in.ImageSource.DeepCopyInto(&out.ImageSource)
	if in.RollbackOnFailure != nil {
		in, out := &in.RollbackOnFailure, &out.RollbackOnFailure
		*out = new(bool)
		**out = **in
	}
	if in.MaintenanceWindow != nil {
		in, out := &in.MaintenanceWindow, &out.MaintenanceWindow
		*out = new(UpgradeWindow)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXESoftwareUpgradeSpec.
func (in *IOSXESoftwareUpgradeSpec) DeepCopy() *IOSXESoftwareUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(IOSXESoftwareUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IOSXESoftwareUpgradeStatus) DeepCopyInto(out *IOSXESoftwareUpgradeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransferProgress != nil {
		in, out := &in.TransferProgress, &out.TransferProgress
		*out = new(UpgradeTransferProgress)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IOSXESoftwareUpgradeStatus.
func (in *IOSXESoftwareUpgradeStatus) DeepCopy() *IOSXESoftwareUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(IOSXESoftwareUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KillProcessArgs) DeepCopyInto(out *KillProcessArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KillProcessArgs.
func (in *KillProcessArgs) DeepCopy() *KillProcessArgs {
	if in == nil {
		return nil
	}
	out := new(KillProcessArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootActionArgs) DeepCopyInto(out *RebootActionArgs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootActionArgs.
func (in *RebootActionArgs) DeepCopy() *RebootActionArgs {
	if in == nil {
		return nil
	}
	out := new(RebootActionArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeImageSource) DeepCopyInto(out *UpgradeImageSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeImageSource.
func (in *UpgradeImageSource) DeepCopy() *UpgradeImageSource {
	if in == nil {
		return nil
	}
	out := new(UpgradeImageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeTransferProgress) DeepCopyInto(out *UpgradeTransferProgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeTransferProgress.
func (in *UpgradeTransferProgress) DeepCopy() *UpgradeTransferProgress {
	if in == nil {
		return nil
	}
	out := new(UpgradeTransferProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeWindow) DeepCopyInto(out *UpgradeWindow) {
	*out = *in
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeWindow.
func (in *UpgradeWindow) DeepCopy() *UpgradeWindow {
	if in == nil {
		return nil
	}
	out := new(UpgradeWindow)
	in.DeepCopyInto(out)
	return out
}
