apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - defaults/iosxeconfigdefaults.yaml
  - device-groups/access-switches.yaml
  - templates/standard-uplink.yaml
  - devices/edge-01
  - apps/nginx/pod.yaml
