//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiscoDevice) DeepCopyInto(out *CiscoDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiscoDevice.
func (in *CiscoDevice) DeepCopy() *CiscoDevice {
	if in == nil {
		return nil
	}
	out := new(CiscoDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiscoDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiscoDeviceList) DeepCopyInto(out *CiscoDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CiscoDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiscoDeviceList.
func (in *CiscoDeviceList) DeepCopy() *CiscoDeviceList {
	if in == nil {
		return nil
	}
	out := new(CiscoDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiscoDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigPrereqs) DeepCopyInto(out *ConfigPrereqs) {
	*out = *in
	if in.ManagedFamilies != nil {
		in, out := &in.ManagedFamilies, &out.ManagedFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigPrereqs.
func (in *ConfigPrereqs) DeepCopy() *ConfigPrereqs {
	if in == nil {
		return nil
	}
	out := new(ConfigPrereqs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourceLimits.DeepCopyInto(&out.ResourceLimits)
	if in.OTEL != nil {
		in, out := &in.OTEL, &out.OTEL
		*out = new(OTELConfig)
		**out = **in
	}
	if in.ConfigPrereqs != nil {
		in, out := &in.ConfigPrereqs, &out.ConfigPrereqs
		*out = new(ConfigPrereqs)
		(*in).DeepCopyInto(*out)
	}
	if in.OpsPolicy != nil {
		in, out := &in.OpsPolicy, &out.OpsPolicy
		*out = new(OpsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.XE != nil {
		in, out := &in.XE, &out.XE
		*out = new(XEConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NXOS != nil {
		in, out := &in.NXOS, &out.NXOS
		*out = new(NXOSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSpec.
func (in *DeviceSpec) DeepCopy() *DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkerCapabilities != nil {
		in, out := &in.WorkerCapabilities, &out.WorkerCapabilities
		*out = make([]WorkerCapabilityStatus, len(*in))
		copy(*out, *in)
	}
	if in.NetAsCode != nil {
		in, out := &in.NetAsCode, &out.NetAsCode
		*out = new(NetAsCodeModelStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSConfig) DeepCopyInto(out *NXOSConfig) {
	*out = *in
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(NXOSNetworkingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSConfig.
func (in *NXOSConfig) DeepCopy() *NXOSConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSInterfaceConfig) DeepCopyInto(out *NXOSInterfaceConfig) {
	*out = *in
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(NXOSManagementInterfaceConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSInterfaceConfig.
func (in *NXOSInterfaceConfig) DeepCopy() *NXOSInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSManagementInterfaceConfig) DeepCopyInto(out *NXOSManagementInterfaceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSManagementInterfaceConfig.
func (in *NXOSManagementInterfaceConfig) DeepCopy() *NXOSManagementInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSManagementInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSNetworkingConfig) DeepCopyInto(out *NXOSNetworkingConfig) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(NXOSInterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSNetworkingConfig.
func (in *NXOSNetworkingConfig) DeepCopy() *NXOSNetworkingConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSNetworkingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAsCodeModelStatus) DeepCopyInto(out *NetAsCodeModelStatus) {
	*out = *in
	if in.Sections != nil {
		in, out := &in.Sections, &out.Sections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAsCodeModelStatus.
func (in *NetAsCodeModelStatus) DeepCopy() *NetAsCodeModelStatus {
	if in == nil {
		return nil
	}
	out := new(NetAsCodeModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkController) DeepCopyInto(out *NetworkController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkController.
func (in *NetworkController) DeepCopy() *NetworkController {
	if in == nil {
		return nil
	}
	out := new(NetworkController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerCapabilityStatus) DeepCopyInto(out *NetworkControllerCapabilityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerCapabilityStatus.
func (in *NetworkControllerCapabilityStatus) DeepCopy() *NetworkControllerCapabilityStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerCapabilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerConfigMapKeyReference) DeepCopyInto(out *NetworkControllerConfigMapKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerConfigMapKeyReference.
func (in *NetworkControllerConfigMapKeyReference) DeepCopy() *NetworkControllerConfigMapKeyReference {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerConfigMapKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerConnectionPolicy) DeepCopyInto(out *NetworkControllerConnectionPolicy) {
	*out = *in
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HealthCheckInterval != nil {
		in, out := &in.HealthCheckInterval, &out.HealthCheckInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(NetworkControllerRateLimit)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerConnectionPolicy.
func (in *NetworkControllerConnectionPolicy) DeepCopy() *NetworkControllerConnectionPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerConnectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerIntentSecretSource) DeepCopyInto(out *NetworkControllerIntentSecretSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerIntentSecretSource.
func (in *NetworkControllerIntentSecretSource) DeepCopy() *NetworkControllerIntentSecretSource {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerIntentSecretSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerList) DeepCopyInto(out *NetworkControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerList.
func (in *NetworkControllerList) DeepCopy() *NetworkControllerList {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerNetAsCodeStatus) DeepCopyInto(out *NetworkControllerNetAsCodeStatus) {
	*out = *in
	if in.ModelVersions != nil {
		in, out := &in.ModelVersions, &out.ModelVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sections != nil {
		in, out := &in.Sections, &out.Sections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerNetAsCodeStatus.
func (in *NetworkControllerNetAsCodeStatus) DeepCopy() *NetworkControllerNetAsCodeStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerNetAsCodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerRateLimit) DeepCopyInto(out *NetworkControllerRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerRateLimit.
func (in *NetworkControllerRateLimit) DeepCopy() *NetworkControllerRateLimit {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerSecretReference) DeepCopyInto(out *NetworkControllerSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerSecretReference.
func (in *NetworkControllerSecretReference) DeepCopy() *NetworkControllerSecretReference {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerSpec) DeepCopyInto(out *NetworkControllerSpec) {
	*out = *in
	out.CredentialSecretRef = in.CredentialSecretRef
	if in.IntentSecretSources != nil {
		in, out := &in.IntentSecretSources, &out.IntentSecretSources
		*out = make([]NetworkControllerIntentSecretSource, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(NetworkControllerTLSConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerSpec.
func (in *NetworkControllerSpec) DeepCopy() *NetworkControllerSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerStatus) DeepCopyInto(out *NetworkControllerStatus) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulConnectionTime != nil {
		in, out := &in.LastSuccessfulConnectionTime, &out.LastSuccessfulConnectionTime
		*out = (*in).DeepCopy()
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]NetworkControllerCapabilityStatus, len(*in))
		copy(*out, *in)
	}
	if in.NetAsCode != nil {
		in, out := &in.NetAsCode, &out.NetAsCode
		*out = new(NetworkControllerNetAsCodeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(NetworkControllerWorkerStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerStatus.
func (in *NetworkControllerStatus) DeepCopy() *NetworkControllerStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerTLSConfig) DeepCopyInto(out *NetworkControllerTLSConfig) {
	*out = *in
	if in.CAConfigMapRef != nil {
		in, out := &in.CAConfigMapRef, &out.CAConfigMapRef
		*out = new(NetworkControllerConfigMapKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerTLSConfig.
func (in *NetworkControllerTLSConfig) DeepCopy() *NetworkControllerTLSConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerWorkerStatus) DeepCopyInto(out *NetworkControllerWorkerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerWorkerStatus.
func (in *NetworkControllerWorkerStatus) DeepCopy() *NetworkControllerWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerWorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTELConfig) DeepCopyInto(out *OTELConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTELConfig.
func (in *OTELConfig) DeepCopy() *OTELConfig {
	if in == nil {
		return nil
	}
	out := new(OTELConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsPolicy) DeepCopyInto(out *OpsPolicy) {
	*out = *in
	if in.ConfigDiffAllowedNamespaces != nil {
		in, out := &in.ConfigDiffAllowedNamespaces, &out.ConfigDiffAllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsPolicy.
func (in *OpsPolicy) DeepCopy() *OpsPolicy {
	if in == nil {
		return nil
	}
	out := new(OpsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.Others != nil {
		in, out := &in.Others, &out.Others
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerCapabilityStatus) DeepCopyInto(out *WorkerCapabilityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerCapabilityStatus.
func (in *WorkerCapabilityStatus) DeepCopy() *WorkerCapabilityStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerCapabilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEAppGigabitEthernetConfig) DeepCopyInto(out *XEAppGigabitEthernetConfig) {
	*out = *in
	out.VlanIf = in.VlanIf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEAppGigabitEthernetConfig.
func (in *XEAppGigabitEthernetConfig) DeepCopy() *XEAppGigabitEthernetConfig {
	if in == nil {
		return nil
	}
	out := new(XEAppGigabitEthernetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEConfig) DeepCopyInto(out *XEConfig) {
	*out = *in
	in.Networking.DeepCopyInto(&out.Networking)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEConfig.
func (in *XEConfig) DeepCopy() *XEConfig {
	if in == nil {
		return nil
	}
	out := new(XEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEInterfaceConfig) DeepCopyInto(out *XEInterfaceConfig) {
	*out = *in
	if in.VirtualPortGroup != nil {
		in, out := &in.VirtualPortGroup, &out.VirtualPortGroup
		*out = new(XEVirtualPortGroupConfig)
		**out = **in
	}
	if in.AppGigabitEthernet != nil {
		in, out := &in.AppGigabitEthernet, &out.AppGigabitEthernet
		*out = new(XEAppGigabitEthernetConfig)
		**out = **in
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(XEManagementConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEInterfaceConfig.
func (in *XEInterfaceConfig) DeepCopy() *XEInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(XEInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEManagementConfig) DeepCopyInto(out *XEManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEManagementConfig.
func (in *XEManagementConfig) DeepCopy() *XEManagementConfig {
	if in == nil {
		return nil
	}
	out := new(XEManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XENetworkConfig) DeepCopyInto(out *XENetworkConfig) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(XEInterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XENetworkConfig.
func (in *XENetworkConfig) DeepCopy() *XENetworkConfig {
	if in == nil {
		return nil
	}
	out := new(XENetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEVirtualPortGroupConfig) DeepCopyInto(out *XEVirtualPortGroupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEVirtualPortGroupConfig.
func (in *XEVirtualPortGroupConfig) DeepCopy() *XEVirtualPortGroupConfig {
	if in == nil {
		return nil
	}
	out := new(XEVirtualPortGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEVlanInterfaceConfig) DeepCopyInto(out *XEVlanInterfaceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEVlanInterfaceConfig.
func (in *XEVlanInterfaceConfig) DeepCopy() *XEVlanInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(XEVlanInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}
