//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiscoDevice) DeepCopyInto(out *CiscoDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiscoDevice.
func (in *CiscoDevice) DeepCopy() *CiscoDevice {
	if in == nil {
		return nil
	}
	out := new(CiscoDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiscoDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiscoDeviceList) DeepCopyInto(out *CiscoDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CiscoDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiscoDeviceList.
func (in *CiscoDeviceList) DeepCopy() *CiscoDeviceList {
	if in == nil {
		return nil
	}
	out := new(CiscoDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiscoDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigPrereqs) DeepCopyInto(out *ConfigPrereqs) {
	*out = *in
	if in.ManagedFamilies != nil {
		in, out := &in.ManagedFamilies, &out.ManagedFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigPrereqs.
func (in *ConfigPrereqs) DeepCopy() *ConfigPrereqs {
	if in == nil {
		return nil
	}
	out := new(ConfigPrereqs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceConditionObservationStatus) DeepCopyInto(out *DeviceConditionObservationStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceConditionObservationStatus.
func (in *DeviceConditionObservationStatus) DeepCopy() *DeviceConditionObservationStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceConditionObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceHealthObservationStatus) DeepCopyInto(out *DeviceHealthObservationStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	in.NodeReadyHeartbeatTime.DeepCopyInto(&out.NodeReadyHeartbeatTime)
	if in.ConditionObservations != nil {
		in, out := &in.ConditionObservations, &out.ConditionObservations
		*out = make([]DeviceConditionObservationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceHealthObservationStatus.
func (in *DeviceHealthObservationStatus) DeepCopy() *DeviceHealthObservationStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceHealthObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceLegacyHandoffStatus) DeepCopyInto(out *DeviceLegacyHandoffStatus) {
	*out = *in
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
	if in.NodeReleasedAt != nil {
		in, out := &in.NodeReleasedAt, &out.NodeReleasedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceLegacyHandoffStatus.
func (in *DeviceLegacyHandoffStatus) DeepCopy() *DeviceLegacyHandoffStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceLegacyHandoffStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceMaintenanceLeaseReference) DeepCopyInto(out *DeviceMaintenanceLeaseReference) {
	*out = *in
	out.DeviceMaintenanceObjectReference = in.DeviceMaintenanceObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceMaintenanceLeaseReference.
func (in *DeviceMaintenanceLeaseReference) DeepCopy() *DeviceMaintenanceLeaseReference {
	if in == nil {
		return nil
	}
	out := new(DeviceMaintenanceLeaseReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceMaintenanceObjectReference) DeepCopyInto(out *DeviceMaintenanceObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceMaintenanceObjectReference.
func (in *DeviceMaintenanceObjectReference) DeepCopy() *DeviceMaintenanceObjectReference {
	if in == nil {
		return nil
	}
	out := new(DeviceMaintenanceObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceMaintenanceSessionStatus) DeepCopyInto(out *DeviceMaintenanceSessionStatus) {
	*out = *in
	out.Lease = in.Lease
	out.Operation = in.Operation
	in.RequestedAt.DeepCopyInto(&out.RequestedAt)
	if in.AcknowledgedAt != nil {
		in, out := &in.AcknowledgedAt, &out.AcknowledgedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceMaintenanceSessionStatus.
func (in *DeviceMaintenanceSessionStatus) DeepCopy() *DeviceMaintenanceSessionStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceMaintenanceSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceNodeIdentityStatus) DeepCopyInto(out *DeviceNodeIdentityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceNodeIdentityStatus.
func (in *DeviceNodeIdentityStatus) DeepCopy() *DeviceNodeIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceNodeIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
	if in.GNOI != nil {
		in, out := &in.GNOI, &out.GNOI
		*out = new(GNOIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourceLimits.DeepCopyInto(&out.ResourceLimits)
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(DeviceWorkerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OTEL != nil {
		in, out := &in.OTEL, &out.OTEL
		*out = new(OTELConfig)
		**out = **in
	}
	if in.ConfigPrereqs != nil {
		in, out := &in.ConfigPrereqs, &out.ConfigPrereqs
		*out = new(ConfigPrereqs)
		(*in).DeepCopyInto(*out)
	}
	if in.OpsPolicy != nil {
		in, out := &in.OpsPolicy, &out.OpsPolicy
		*out = new(OpsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.XE != nil {
		in, out := &in.XE, &out.XE
		*out = new(XEConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NXOS != nil {
		in, out := &in.NXOS, &out.NXOS
		*out = new(NXOSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSpec.
func (in *DeviceSpec) DeepCopy() *DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeIdentity != nil {
		in, out := &in.NodeIdentity, &out.NodeIdentity
		*out = new(DeviceNodeIdentityStatus)
		**out = **in
	}
	if in.TopologyProjection != nil {
		in, out := &in.TopologyProjection, &out.TopologyProjection
		*out = new(DeviceTopologyProjectionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthObservation != nil {
		in, out := &in.HealthObservation, &out.HealthObservation
		*out = new(DeviceHealthObservationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerRevision != nil {
		in, out := &in.WorkerRevision, &out.WorkerRevision
		*out = new(DeviceWorkerRevisionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LegacyHandoff != nil {
		in, out := &in.LegacyHandoff, &out.LegacyHandoff
		*out = new(DeviceLegacyHandoffStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyLock != nil {
		in, out := &in.TopologyLock, &out.TopologyLock
		*out = new(DeviceTopologyLockStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.MaintenanceSession != nil {
		in, out := &in.MaintenanceSession, &out.MaintenanceSession
		*out = new(DeviceMaintenanceSessionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerCapabilities != nil {
		in, out := &in.WorkerCapabilities, &out.WorkerCapabilities
		*out = make([]WorkerCapabilityStatus, len(*in))
		copy(*out, *in)
	}
	if in.NetAsCode != nil {
		in, out := &in.NetAsCode, &out.NetAsCode
		*out = new(NetAsCodeModelStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceTopologyLockStatus) DeepCopyInto(out *DeviceTopologyLockStatus) {
	*out = *in
	in.AcquiredAt.DeepCopyInto(&out.AcquiredAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceTopologyLockStatus.
func (in *DeviceTopologyLockStatus) DeepCopy() *DeviceTopologyLockStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceTopologyLockStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceTopologyProjectionStatus) DeepCopyInto(out *DeviceTopologyProjectionStatus) {
	*out = *in
	in.LastSuccessfulTime.DeepCopyInto(&out.LastSuccessfulTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceTopologyProjectionStatus.
func (in *DeviceTopologyProjectionStatus) DeepCopy() *DeviceTopologyProjectionStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceTopologyProjectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceWorkerConfig) DeepCopyInto(out *DeviceWorkerConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(DeviceWorkerResources)
		(*in).DeepCopyInto(*out)
	}
	if in.TmpSizeLimit != nil {
		in, out := &in.TmpSizeLimit, &out.TmpSizeLimit
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceWorkerConfig.
func (in *DeviceWorkerConfig) DeepCopy() *DeviceWorkerConfig {
	if in == nil {
		return nil
	}
	out := new(DeviceWorkerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceWorkerResources) DeepCopyInto(out *DeviceWorkerResources) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceWorkerResources.
func (in *DeviceWorkerResources) DeepCopy() *DeviceWorkerResources {
	if in == nil {
		return nil
	}
	out := new(DeviceWorkerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceWorkerRevisionStatus) DeepCopyInto(out *DeviceWorkerRevisionStatus) {
	*out = *in
	if in.PodStartTime != nil {
		in, out := &in.PodStartTime, &out.PodStartTime
		*out = (*in).DeepCopy()
	}
	if in.ReadyHeartbeatTime != nil {
		in, out := &in.ReadyHeartbeatTime, &out.ReadyHeartbeatTime
		*out = (*in).DeepCopy()
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceWorkerRevisionStatus.
func (in *DeviceWorkerRevisionStatus) DeepCopy() *DeviceWorkerRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceWorkerRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOIConfig) DeepCopyInto(out *GNOIConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(GNOITLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOIConfig.
func (in *GNOIConfig) DeepCopy() *GNOIConfig {
	if in == nil {
		return nil
	}
	out := new(GNOIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOITLSConfig) DeepCopyInto(out *GNOITLSConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(GNOITLSSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOITLSConfig.
func (in *GNOITLSConfig) DeepCopy() *GNOITLSConfig {
	if in == nil {
		return nil
	}
	out := new(GNOITLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GNOITLSSecretReference) DeepCopyInto(out *GNOITLSSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GNOITLSSecretReference.
func (in *GNOITLSSecretReference) DeepCopy() *GNOITLSSecretReference {
	if in == nil {
		return nil
	}
	out := new(GNOITLSSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSConfig) DeepCopyInto(out *NXOSConfig) {
	*out = *in
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(NXOSNetworkingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSConfig.
func (in *NXOSConfig) DeepCopy() *NXOSConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSInterfaceConfig) DeepCopyInto(out *NXOSInterfaceConfig) {
	*out = *in
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(NXOSManagementInterfaceConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSInterfaceConfig.
func (in *NXOSInterfaceConfig) DeepCopy() *NXOSInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSManagementInterfaceConfig) DeepCopyInto(out *NXOSManagementInterfaceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSManagementInterfaceConfig.
func (in *NXOSManagementInterfaceConfig) DeepCopy() *NXOSManagementInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSManagementInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSNetworkingConfig) DeepCopyInto(out *NXOSNetworkingConfig) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(NXOSInterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSNetworkingConfig.
func (in *NXOSNetworkingConfig) DeepCopy() *NXOSNetworkingConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSNetworkingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetAsCodeModelStatus) DeepCopyInto(out *NetAsCodeModelStatus) {
	*out = *in
	if in.Sections != nil {
		in, out := &in.Sections, &out.Sections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetAsCodeModelStatus.
func (in *NetAsCodeModelStatus) DeepCopy() *NetAsCodeModelStatus {
	if in == nil {
		return nil
	}
	out := new(NetAsCodeModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkController) DeepCopyInto(out *NetworkController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkController.
func (in *NetworkController) DeepCopy() *NetworkController {
	if in == nil {
		return nil
	}
	out := new(NetworkController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerCapabilityStatus) DeepCopyInto(out *NetworkControllerCapabilityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerCapabilityStatus.
func (in *NetworkControllerCapabilityStatus) DeepCopy() *NetworkControllerCapabilityStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerCapabilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerConfigMapKeyReference) DeepCopyInto(out *NetworkControllerConfigMapKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerConfigMapKeyReference.
func (in *NetworkControllerConfigMapKeyReference) DeepCopy() *NetworkControllerConfigMapKeyReference {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerConfigMapKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerConnectionPolicy) DeepCopyInto(out *NetworkControllerConnectionPolicy) {
	*out = *in
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HealthCheckInterval != nil {
		in, out := &in.HealthCheckInterval, &out.HealthCheckInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(NetworkControllerRateLimit)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerConnectionPolicy.
func (in *NetworkControllerConnectionPolicy) DeepCopy() *NetworkControllerConnectionPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerConnectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerIntentSecretSource) DeepCopyInto(out *NetworkControllerIntentSecretSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerIntentSecretSource.
func (in *NetworkControllerIntentSecretSource) DeepCopy() *NetworkControllerIntentSecretSource {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerIntentSecretSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerList) DeepCopyInto(out *NetworkControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerList.
func (in *NetworkControllerList) DeepCopy() *NetworkControllerList {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerNetAsCodeStatus) DeepCopyInto(out *NetworkControllerNetAsCodeStatus) {
	*out = *in
	if in.ModelVersions != nil {
		in, out := &in.ModelVersions, &out.ModelVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sections != nil {
		in, out := &in.Sections, &out.Sections
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerNetAsCodeStatus.
func (in *NetworkControllerNetAsCodeStatus) DeepCopy() *NetworkControllerNetAsCodeStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerNetAsCodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerRateLimit) DeepCopyInto(out *NetworkControllerRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerRateLimit.
func (in *NetworkControllerRateLimit) DeepCopy() *NetworkControllerRateLimit {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerSecretReference) DeepCopyInto(out *NetworkControllerSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerSecretReference.
func (in *NetworkControllerSecretReference) DeepCopy() *NetworkControllerSecretReference {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerSpec) DeepCopyInto(out *NetworkControllerSpec) {
	*out = *in
	out.CredentialSecretRef = in.CredentialSecretRef
	if in.IntentSecretSources != nil {
		in, out := &in.IntentSecretSources, &out.IntentSecretSources
		*out = make([]NetworkControllerIntentSecretSource, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(NetworkControllerTLSConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerSpec.
func (in *NetworkControllerSpec) DeepCopy() *NetworkControllerSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerStatus) DeepCopyInto(out *NetworkControllerStatus) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulConnectionTime != nil {
		in, out := &in.LastSuccessfulConnectionTime, &out.LastSuccessfulConnectionTime
		*out = (*in).DeepCopy()
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]NetworkControllerCapabilityStatus, len(*in))
		copy(*out, *in)
	}
	if in.NetAsCode != nil {
		in, out := &in.NetAsCode, &out.NetAsCode
		*out = new(NetworkControllerNetAsCodeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(NetworkControllerWorkerStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerStatus.
func (in *NetworkControllerStatus) DeepCopy() *NetworkControllerStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerTLSConfig) DeepCopyInto(out *NetworkControllerTLSConfig) {
	*out = *in
	if in.CAConfigMapRef != nil {
		in, out := &in.CAConfigMapRef, &out.CAConfigMapRef
		*out = new(NetworkControllerConfigMapKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerTLSConfig.
func (in *NetworkControllerTLSConfig) DeepCopy() *NetworkControllerTLSConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkControllerWorkerStatus) DeepCopyInto(out *NetworkControllerWorkerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkControllerWorkerStatus.
func (in *NetworkControllerWorkerStatus) DeepCopy() *NetworkControllerWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkControllerWorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTELConfig) DeepCopyInto(out *OTELConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTELConfig.
func (in *OTELConfig) DeepCopy() *OTELConfig {
	if in == nil {
		return nil
	}
	out := new(OTELConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsPolicy) DeepCopyInto(out *OpsPolicy) {
	*out = *in
	if in.ConfigDiffAllowedNamespaces != nil {
		in, out := &in.ConfigDiffAllowedNamespaces, &out.ConfigDiffAllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsPolicy.
func (in *OpsPolicy) DeepCopy() *OpsPolicy {
	if in == nil {
		return nil
	}
	out := new(OpsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.Others != nil {
		in, out := &in.Others, &out.Others
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerCapabilityStatus) DeepCopyInto(out *WorkerCapabilityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerCapabilityStatus.
func (in *WorkerCapabilityStatus) DeepCopy() *WorkerCapabilityStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerCapabilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEAppGigabitEthernetConfig) DeepCopyInto(out *XEAppGigabitEthernetConfig) {
	*out = *in
	out.VlanIf = in.VlanIf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEAppGigabitEthernetConfig.
func (in *XEAppGigabitEthernetConfig) DeepCopy() *XEAppGigabitEthernetConfig {
	if in == nil {
		return nil
	}
	out := new(XEAppGigabitEthernetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEConfig) DeepCopyInto(out *XEConfig) {
	*out = *in
	in.Networking.DeepCopyInto(&out.Networking)
	if in.GNOI != nil {
		in, out := &in.GNOI, &out.GNOI
		*out = new(XEGNOIConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEConfig.
func (in *XEConfig) DeepCopy() *XEConfig {
	if in == nil {
		return nil
	}
	out := new(XEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEGNOICertificateProvisioning) DeepCopyInto(out *XEGNOICertificateProvisioning) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEGNOICertificateProvisioning.
func (in *XEGNOICertificateProvisioning) DeepCopy() *XEGNOICertificateProvisioning {
	if in == nil {
		return nil
	}
	out := new(XEGNOICertificateProvisioning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEGNOIConfig) DeepCopyInto(out *XEGNOIConfig) {
	*out = *in
	if in.CertificateProvisioning != nil {
		in, out := &in.CertificateProvisioning, &out.CertificateProvisioning
		*out = new(XEGNOICertificateProvisioning)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEGNOIConfig.
func (in *XEGNOIConfig) DeepCopy() *XEGNOIConfig {
	if in == nil {
		return nil
	}
	out := new(XEGNOIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEGNOIProvisioningSecretReference) DeepCopyInto(out *XEGNOIProvisioningSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEGNOIProvisioningSecretReference.
func (in *XEGNOIProvisioningSecretReference) DeepCopy() *XEGNOIProvisioningSecretReference {
	if in == nil {
		return nil
	}
	out := new(XEGNOIProvisioningSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEInterfaceConfig) DeepCopyInto(out *XEInterfaceConfig) {
	*out = *in
	if in.VirtualPortGroup != nil {
		in, out := &in.VirtualPortGroup, &out.VirtualPortGroup
		*out = new(XEVirtualPortGroupConfig)
		**out = **in
	}
	if in.AppGigabitEthernet != nil {
		in, out := &in.AppGigabitEthernet, &out.AppGigabitEthernet
		*out = new(XEAppGigabitEthernetConfig)
		**out = **in
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(XEManagementConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEInterfaceConfig.
func (in *XEInterfaceConfig) DeepCopy() *XEInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(XEInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEManagementConfig) DeepCopyInto(out *XEManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEManagementConfig.
func (in *XEManagementConfig) DeepCopy() *XEManagementConfig {
	if in == nil {
		return nil
	}
	out := new(XEManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XENetworkConfig) DeepCopyInto(out *XENetworkConfig) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(XEInterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XENetworkConfig.
func (in *XENetworkConfig) DeepCopy() *XENetworkConfig {
	if in == nil {
		return nil
	}
	out := new(XENetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEVirtualPortGroupConfig) DeepCopyInto(out *XEVirtualPortGroupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEVirtualPortGroupConfig.
func (in *XEVirtualPortGroupConfig) DeepCopy() *XEVirtualPortGroupConfig {
	if in == nil {
		return nil
	}
	out := new(XEVirtualPortGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEVlanInterfaceConfig) DeepCopyInto(out *XEVlanInterfaceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEVlanInterfaceConfig.
func (in *XEVlanInterfaceConfig) DeepCopy() *XEVlanInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(XEVlanInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}
