//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiscoDevice) DeepCopyInto(out *CiscoDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiscoDevice.
func (in *CiscoDevice) DeepCopy() *CiscoDevice {
	if in == nil {
		return nil
	}
	out := new(CiscoDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiscoDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiscoDeviceList) DeepCopyInto(out *CiscoDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CiscoDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiscoDeviceList.
func (in *CiscoDeviceList) DeepCopy() *CiscoDeviceList {
	if in == nil {
		return nil
	}
	out := new(CiscoDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CiscoDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigPrereqs) DeepCopyInto(out *ConfigPrereqs) {
	*out = *in
	in.Configuration.DeepCopyInto(&out.Configuration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigPrereqs.
func (in *ConfigPrereqs) DeepCopy() *ConfigPrereqs {
	if in == nil {
		return nil
	}
	out := new(ConfigPrereqs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
	if in.CredentialSecretRef != nil {
		in, out := &in.CredentialSecretRef, &out.CredentialSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]v1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ResourceLimits.DeepCopyInto(&out.ResourceLimits)
	if in.OTEL != nil {
		in, out := &in.OTEL, &out.OTEL
		*out = new(OTELConfig)
		**out = **in
	}
	if in.ConfigPrereqs != nil {
		in, out := &in.ConfigPrereqs, &out.ConfigPrereqs
		*out = new(ConfigPrereqs)
		(*in).DeepCopyInto(*out)
	}
	if in.OpsPolicy != nil {
		in, out := &in.OpsPolicy, &out.OpsPolicy
		*out = new(OpsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.XE != nil {
		in, out := &in.XE, &out.XE
		*out = new(XEConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.XR != nil {
		in, out := &in.XR, &out.XR
		*out = new(XRConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NXOS != nil {
		in, out := &in.NXOS, &out.NXOS
		*out = new(NXOSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FTD != nil {
		in, out := &in.FTD, &out.FTD
		*out = new(FTDConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ISE != nil {
		in, out := &in.ISE, &out.ISE
		*out = new(ISEConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSpec.
func (in *DeviceSpec) DeepCopy() *DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FTDConfig) DeepCopyInto(out *FTDConfig) {
	*out = *in
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(FTDManagementConfig)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(FTDResourceConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FTDConfig.
func (in *FTDConfig) DeepCopy() *FTDConfig {
	if in == nil {
		return nil
	}
	out := new(FTDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FTDManagementConfig) DeepCopyInto(out *FTDManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FTDManagementConfig.
func (in *FTDManagementConfig) DeepCopy() *FTDManagementConfig {
	if in == nil {
		return nil
	}
	out := new(FTDManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FTDResourceConfig) DeepCopyInto(out *FTDResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FTDResourceConfig.
func (in *FTDResourceConfig) DeepCopy() *FTDResourceConfig {
	if in == nil {
		return nil
	}
	out := new(FTDResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISEAPIConfig) DeepCopyInto(out *ISEAPIConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISEAPIConfig.
func (in *ISEAPIConfig) DeepCopy() *ISEAPIConfig {
	if in == nil {
		return nil
	}
	out := new(ISEAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISEConfig) DeepCopyInto(out *ISEConfig) {
	*out = *in
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(ISEManagementConfig)
		**out = **in
	}
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(ISEAPIConfig)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ISEResourceConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISEConfig.
func (in *ISEConfig) DeepCopy() *ISEConfig {
	if in == nil {
		return nil
	}
	out := new(ISEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISEManagementConfig) DeepCopyInto(out *ISEManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISEManagementConfig.
func (in *ISEManagementConfig) DeepCopy() *ISEManagementConfig {
	if in == nil {
		return nil
	}
	out := new(ISEManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISEResourceConfig) DeepCopyInto(out *ISEResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISEResourceConfig.
func (in *ISEResourceConfig) DeepCopy() *ISEResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ISEResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSConfig) DeepCopyInto(out *NXOSConfig) {
	*out = *in
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(NXOSNetworkingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSConfig.
func (in *NXOSConfig) DeepCopy() *NXOSConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSInterfaceConfig) DeepCopyInto(out *NXOSInterfaceConfig) {
	*out = *in
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(NXOSManagementInterfaceConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSInterfaceConfig.
func (in *NXOSInterfaceConfig) DeepCopy() *NXOSInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSManagementInterfaceConfig) DeepCopyInto(out *NXOSManagementInterfaceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSManagementInterfaceConfig.
func (in *NXOSManagementInterfaceConfig) DeepCopy() *NXOSManagementInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSManagementInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NXOSNetworkingConfig) DeepCopyInto(out *NXOSNetworkingConfig) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(NXOSInterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NXOSNetworkingConfig.
func (in *NXOSNetworkingConfig) DeepCopy() *NXOSNetworkingConfig {
	if in == nil {
		return nil
	}
	out := new(NXOSNetworkingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTELConfig) DeepCopyInto(out *OTELConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTELConfig.
func (in *OTELConfig) DeepCopy() *OTELConfig {
	if in == nil {
		return nil
	}
	out := new(OTELConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsPolicy) DeepCopyInto(out *OpsPolicy) {
	*out = *in
	if in.ConfigDiffAllowedNamespaces != nil {
		in, out := &in.ConfigDiffAllowedNamespaces, &out.ConfigDiffAllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsPolicy.
func (in *OpsPolicy) DeepCopy() *OpsPolicy {
	if in == nil {
		return nil
	}
	out := new(OpsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.Others != nil {
		in, out := &in.Others, &out.Others
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEAppGigabitEthernetConfig) DeepCopyInto(out *XEAppGigabitEthernetConfig) {
	*out = *in
	out.VlanIf = in.VlanIf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEAppGigabitEthernetConfig.
func (in *XEAppGigabitEthernetConfig) DeepCopy() *XEAppGigabitEthernetConfig {
	if in == nil {
		return nil
	}
	out := new(XEAppGigabitEthernetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEConfig) DeepCopyInto(out *XEConfig) {
	*out = *in
	in.Networking.DeepCopyInto(&out.Networking)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEConfig.
func (in *XEConfig) DeepCopy() *XEConfig {
	if in == nil {
		return nil
	}
	out := new(XEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEInterfaceConfig) DeepCopyInto(out *XEInterfaceConfig) {
	*out = *in
	if in.VirtualPortGroup != nil {
		in, out := &in.VirtualPortGroup, &out.VirtualPortGroup
		*out = new(XEVirtualPortGroupConfig)
		**out = **in
	}
	if in.AppGigabitEthernet != nil {
		in, out := &in.AppGigabitEthernet, &out.AppGigabitEthernet
		*out = new(XEAppGigabitEthernetConfig)
		**out = **in
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(XEManagementConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEInterfaceConfig.
func (in *XEInterfaceConfig) DeepCopy() *XEInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(XEInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEManagementConfig) DeepCopyInto(out *XEManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEManagementConfig.
func (in *XEManagementConfig) DeepCopy() *XEManagementConfig {
	if in == nil {
		return nil
	}
	out := new(XEManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XENetworkConfig) DeepCopyInto(out *XENetworkConfig) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(XEInterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XENetworkConfig.
func (in *XENetworkConfig) DeepCopy() *XENetworkConfig {
	if in == nil {
		return nil
	}
	out := new(XENetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEVirtualPortGroupConfig) DeepCopyInto(out *XEVirtualPortGroupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEVirtualPortGroupConfig.
func (in *XEVirtualPortGroupConfig) DeepCopy() *XEVirtualPortGroupConfig {
	if in == nil {
		return nil
	}
	out := new(XEVirtualPortGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XEVlanInterfaceConfig) DeepCopyInto(out *XEVlanInterfaceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XEVlanInterfaceConfig.
func (in *XEVlanInterfaceConfig) DeepCopy() *XEVlanInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(XEVlanInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRAppHostingConfig) DeepCopyInto(out *XRAppHostingConfig) {
	*out = *in
	if in.DefaultRunOptions != nil {
		in, out := &in.DefaultRunOptions, &out.DefaultRunOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRAppHostingConfig.
func (in *XRAppHostingConfig) DeepCopy() *XRAppHostingConfig {
	if in == nil {
		return nil
	}
	out := new(XRAppHostingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRConfig) DeepCopyInto(out *XRConfig) {
	*out = *in
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(XRManagementConfig)
		**out = **in
	}
	if in.AppHosting != nil {
		in, out := &in.AppHosting, &out.AppHosting
		*out = new(XRAppHostingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(XRResourceConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRConfig.
func (in *XRConfig) DeepCopy() *XRConfig {
	if in == nil {
		return nil
	}
	out := new(XRConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRManagementConfig) DeepCopyInto(out *XRManagementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRManagementConfig.
func (in *XRManagementConfig) DeepCopy() *XRManagementConfig {
	if in == nil {
		return nil
	}
	out := new(XRManagementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRResourceConfig) DeepCopyInto(out *XRResourceConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRResourceConfig.
func (in *XRResourceConfig) DeepCopy() *XRResourceConfig {
	if in == nil {
		return nil
	}
	out := new(XRResourceConfig)
	in.DeepCopyInto(out)
	return out
}
