// Copyright © 2026 Cisco Systems, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sampleFamilies = `
vlan:
  yang_paths: [/Cisco-IOS-XE-native:native/vlan/Cisco-IOS-XE-vlan:vlan-list]
  shape: keyed_list
  key_fields: [id]
  portal: https://netascode.cisco.com/docs/data_models/iosxe/device/vlan/
vrf:
  yang_paths: [/Cisco-IOS-XE-native:native/vrf/definition]
  shape: keyed_list
  key_fields: [name]
`

func writeTempIndex(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	p := filepath.Join(dir, "families.yaml")
	if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
		t.Fatalf("write tempfile: %v", err)
	}
	return p
}

func TestDryRunReportsLoadedFamilies(t *testing.T) {
	idx := writeTempIndex(t, sampleFamilies)

	var out, errBuf bytes.Buffer
	code := run([]string{"--family-index", idx}, &out, &errBuf)
	if code != exitOK {
		t.Fatalf("exit code = %d (stderr=%q)", code, errBuf.String())
	}
	if !strings.Contains(out.String(), "2 families loaded") {
		t.Errorf("stdout missing family count:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "- vlan ->") {
		t.Errorf("stdout missing vlan entry:\n%s", out.String())
	}
}

func TestMissingFamilyIndex(t *testing.T) {
	var out, errBuf bytes.Buffer
	code := run([]string{"--family-index", "/does/not/exist.yaml"}, &out, &errBuf)
	if code != exitBadInput {
		t.Fatalf("exit code = %d, want exitBadInput", code)
	}
	if !strings.Contains(errBuf.String(), "family index not found") {
		t.Errorf("stderr missing diagnostic:\n%s", errBuf.String())
	}
}

// A non-dry-run against a fresh out-writers directory creates one
// skeleton per family. The generated file must compile when copied
// into a real package — we don't test compilation here (no package
// membership yet), but we verify the canonical skeleton shape.
func TestNonDryRunCreatesSkeletons(t *testing.T) {
	idx := writeTempIndex(t, sampleFamilies)
	outDir := t.TempDir()

	var out, errBuf bytes.Buffer
	code := run([]string{
		"--family-index", idx,
		"--out-writers", outDir,
		"--dry-run=false",
	}, &out, &errBuf)
	if code != exitOK {
		t.Fatalf("exit=%d (stderr=%q)", code, errBuf.String())
	}

	for _, fam := range []string{"vlan", "vrf"} {
		p := filepath.Join(outDir, fam+".go")
		body, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("expected %s: %v", p, err)
		}
		if !strings.Contains(string(body), "registerSkeleton(\""+fam+"\"") {
			t.Errorf("%s: missing registerSkeleton call:\n%s", p, body)
		}
		if !strings.Contains(string(body), "AUTO-GENERATED by cisco-vk-yang-sync") {
			t.Errorf("%s: missing AUTO-GENERATED banner", p)
		}
	}
}

// Re-running on a directory that already has files preserves them by
// default. The --force flag overwrites.
func TestNonDryRunPreservesExistingFiles(t *testing.T) {
	idx := writeTempIndex(t, sampleFamilies)
	outDir := t.TempDir()

	existing := filepath.Join(outDir, "vlan.go")
	handWritten := []byte("// hand-written\npackage writers\n")
	if err := os.WriteFile(existing, handWritten, 0o644); err != nil {
		t.Fatalf("seed: %v", err)
	}

	// Default run preserves.
	var out, errBuf bytes.Buffer
	code := run([]string{
		"--family-index", idx,
		"--out-writers", outDir,
		"--dry-run=false",
	}, &out, &errBuf)
	if code != exitOK {
		t.Fatalf("exit=%d", code)
	}
	got, _ := os.ReadFile(existing)
	if string(got) != string(handWritten) {
		t.Errorf("hand-written file was modified:\n%s", got)
	}

	// --force overwrites.
	out.Reset()
	errBuf.Reset()
	code = run([]string{
		"--family-index", idx,
		"--out-writers", outDir,
		"--dry-run=false",
		"--force",
	}, &out, &errBuf)
	if code != exitOK {
		t.Fatalf("exit=%d with --force", code)
	}
	got, _ = os.ReadFile(existing)
	if !strings.Contains(string(got), "registerSkeleton") {
		t.Errorf("--force did not overwrite hand-written file:\n%s", got)
	}
}

func TestRunAgainstCommittedFamilyIndex(t *testing.T) {
	// Exercising the real checked-in index guards against accidental
	// YAML breakage. Lower bound is the Phase-1 family count (8); no
	// upper bound so subsequent phases don't require updates here.
	var out, errBuf bytes.Buffer
	code := run([]string{
		"--family-index", "../../internal/drivers/iosxe/configdriver/schema/families.yaml",
	}, &out, &errBuf)
	if code != exitOK {
		t.Fatalf("exit=%d (stderr=%q)", code, errBuf.String())
	}
	for _, fam := range []string{"vlan", "vrf", "system", "dhcp"} {
		if !strings.Contains(out.String(), "- "+fam+" ->") {
			t.Errorf("Phase-1 family %q missing from dry-run listing", fam)
		}
	}
}

// parseFlags stays silent on valid input; a stray banner would be
// caught here and flagged in review.
func TestParseFlagsSilentOnValidInput(t *testing.T) {
	var errBuf bytes.Buffer
	if _, err := parseFlags([]string{"--yang-version", "1791"}, &errBuf); err != nil {
		t.Fatalf("parseFlags: %v", err)
	}
	if errBuf.Len() != 0 {
		t.Errorf("parseFlags wrote to stderr: %q", errBuf.String())
	}
}

func TestMalformedYAMLRejected(t *testing.T) {
	idx := writeTempIndex(t, "not: [a, valid, list")
	var out, errBuf bytes.Buffer
	code := run([]string{"--family-index", idx}, &out, &errBuf)
	if code != exitBadInput {
		t.Fatalf("exit=%d", code)
	}
}

func TestEmptyFamilyIndexRejected(t *testing.T) {
	idx := writeTempIndex(t, "")
	var out, errBuf bytes.Buffer
	code := run([]string{"--family-index", idx}, &out, &errBuf)
	if code != exitBadInput {
		t.Fatalf("exit=%d", code)
	}
	if !strings.Contains(errBuf.String(), "empty") {
		t.Errorf("stderr missing 'empty':\n%s", errBuf.String())
	}
}

func TestBuildYgotArgsIncludesAllYangFiles(t *testing.T) {
	dir := t.TempDir()
	for _, f := range []string{"a.yang", "b.yang"} {
		if err := os.WriteFile(filepath.Join(dir, f), []byte("module "+f+" { yang-version 1.1; }\n"), 0o600); err != nil {
			t.Fatalf("seed: %v", err)
		}
	}
	// A non-.yang file should be skipped.
	if err := os.WriteFile(filepath.Join(dir, "readme.md"), []byte("doc"), 0o600); err != nil {
		t.Fatalf("seed: %v", err)
	}

	got, err := buildYgotArgs(flags{yangDir: dir, outTypes: "out"}, nil)
	if err != nil {
		t.Fatalf("buildYgotArgs: %v", err)
	}
	if got.bin != "go" {
		t.Errorf("bin=%q, want 'go'", got.bin)
	}
	joined := strings.Join(got.args, " ")
	if !strings.Contains(joined, "github.com/openconfig/ygot/generator") {
		t.Errorf("missing ygot dep in args: %v", got.args)
	}
	if !strings.Contains(joined, "-package_name=generated") {
		t.Errorf("missing package flag: %v", got.args)
	}
	if !strings.Contains(joined, filepath.Join(dir, "a.yang")) {
		t.Errorf("a.yang missing from args: %v", got.args)
	}
	if !strings.Contains(joined, filepath.Join(dir, "b.yang")) {
		t.Errorf("b.yang missing from args: %v", got.args)
	}
	if strings.Contains(joined, "readme.md") {
		t.Errorf("non-.yang file leaked into args: %v", got.args)
	}
}

func TestBuildYgotArgsRespectsYgotBinOverride(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "x.yang"), []byte("module x { yang-version 1.1; }\n"), 0o600); err != nil {
		t.Fatalf("seed: %v", err)
	}
	got, err := buildYgotArgs(flags{yangDir: dir, outTypes: "out", ygotBin: "/usr/local/bin/generator"}, nil)
	if err != nil {
		t.Fatalf("buildYgotArgs: %v", err)
	}
	if got.bin != "/usr/local/bin/generator" {
		t.Errorf("bin=%q, want override", got.bin)
	}
	// When ygotBin is set we must NOT prepend 'go run ...'.
	if len(got.args) > 0 && got.args[0] == "run" {
		t.Errorf("args leaked 'run': %v", got.args)
	}
}

func TestRunSkipsYgotWhenYangDirUnset(t *testing.T) {
	idx := writeTempIndex(t, sampleFamilies)
	var out, errBuf bytes.Buffer
	code := run([]string{"--family-index", idx, "--dry-run=false",
		"--out-writers", t.TempDir()}, &out, &errBuf)
	if code != exitOK {
		t.Fatalf("exit=%d", code)
	}
	if !strings.Contains(out.String(), "skipping ygot") {
		t.Errorf("expected skip notice, got:\n%s", out.String())
	}
}
