// Copyright © 2026 Cisco Systems, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

// patchGeneratedSchema fixes two classes of ygot code-generation defects that
// arise with the Cisco IOS-XE YANG bundle and prevent the generated file from
// compiling:
//
//  1. Duplicate enum constants — when two YANG enum values (e.g. "-" and ".")
//     both reduce to the same Go identifier suffix (both become "__"), ygot
//     emits two const declarations with the same name. The second declaration
//     is renamed to Name_2, Name_3, etc.
//
//  2. Validate field/method conflict — when a YANG container has a child
//     named "validate", ygot generates a Go struct field named Validate AND a
//     public Validate() method on the same struct, which Go forbids. The
//     public Validate() wrapper (which just calls ΛValidate) is renamed to
//     ValidateDeprecated() for the affected types.
//
// The function reads path, applies the patches, and writes the result back.
// It is intentionally idempotent — running it twice produces the same output.
func patchGeneratedSchema(path string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}

	lines := strings.Split(string(raw), "\n")

	// Pass 0: normalize machine-specific paths in the ygot file-header comment.
	lines = normalizeHeaderPaths(lines)

	// Pass 1: collect type names whose struct body contains a "Validate" field.
	shadowed := collectValidateShadowedTypes(lines)

	// Pass 2: apply fixes.
	patched := applyPatches(lines, shadowed)

	return os.WriteFile(path, []byte(strings.Join(patched, "\n")), 0o644)
}

// normalizeHeaderPaths removes machine-specific absolute path prefixes from
// the ygot-generated file-header comment. ygot embeds the absolute path of
// its own binary and the per-run temp directory used for the YANG closure;
// these differ between macOS and Linux (and between CI runs), causing
// spurious drift. Each such path is reduced to its portable basename or
// module reference so committed files are reproducible across platforms.
func normalizeHeaderPaths(lines []string) []string {
	// "This package was generated by <GOPATH>/github.com/…/names.go"
	reGenerator := regexp.MustCompile(`^(This package was generated by ).+(github\.com/.+)$`)
	// "\t- <TMPDIR>/<closure>/Cisco-IOS-XE-foo.yang"
	reInputFile := regexp.MustCompile(`^(\t- ).+/([^/]+\.yang)$`)
	// "\t- <TMPDIR>/<closure>/..."
	reSourceDir := regexp.MustCompile(`^(\t- ).+/\.\.\.$`)

	out := make([]string, len(lines))
	for i, line := range lines {
		switch {
		case reGenerator.MatchString(line):
			line = reGenerator.ReplaceAllString(line, "${1}${2}")
		case reInputFile.MatchString(line):
			line = reInputFile.ReplaceAllString(line, "${1}${2}")
		case reSourceDir.MatchString(line):
			line = reSourceDir.ReplaceAllString(line, "${1}...")
		}
		out[i] = line
	}
	return out
}

// collectValidateShadowedTypes returns the set of Go type names whose struct
// definition contains a field named exactly "Validate".
//
// The generated code has patterns like:
//
//	type TypeName struct {
//	    ...
//	    Validate  *SomeOtherType  `path:"validate" module:"..."`
//	    ...
//	}
func collectValidateShadowedTypes(lines []string) map[string]bool {
	shadowed := map[string]bool{}
	reType := regexp.MustCompile(`^type (\w+) struct \{`)
	reField := regexp.MustCompile(`^\tValidate\s`) // tab-Validate-whitespace
	var currentType string
	inStruct := 0
	for _, line := range lines {
		if m := reType.FindStringSubmatch(line); m != nil {
			currentType = m[1]
			inStruct = 1
			continue
		}
		if inStruct > 0 {
			if strings.HasPrefix(line, "}") {
				inStruct = 0
				currentType = ""
				continue
			}
			// Nested struct or complex type tracking is not needed since ygot
			// generates flat struct bodies — we only track depth 1.
			if reField.MatchString(line) && currentType != "" {
				shadowed[currentType] = true
			}
		}
	}
	return shadowed
}

// applyPatches applies both fixes to the given lines and returns the patched
// slice.
func applyPatches(lines []string, shadowed map[string]bool) []string {
	out := make([]string, 0, len(lines))

	reConstLine := regexp.MustCompile(`^\t(\w+)\s+(E_\w+)\s*=\s*\d+`)
	reValidateFunc := regexp.MustCompile(`^func \(t \*(\w+)\) Validate\(opts `)
	reValidateComment := regexp.MustCompile(`^// Validate validates s against the YANG schema`)

	inConst := false
	constSeen := map[string]int{}

	// pendingLines holds a comment line that may precede a Validate() func.
	var pendingLines []string
	skipBody := false // set to true while skipping a shadowed Validate() body

	for i := 0; i < len(lines); i++ {
		line := lines[i]

		// — const block tracking for duplicate enum fix —
		if line == "const (" {
			inConst = true
			constSeen = map[string]int{}
			out = append(out, line)
			continue
		}
		if inConst && line == ")" {
			inConst = false
			out = append(out, line)
			continue
		}
		if inConst {
			if m := reConstLine.FindStringSubmatch(line); m != nil {
				name := m[1]
				constSeen[name]++
				if constSeen[name] > 1 {
					// Rename duplicate: append _2, _3, ...
					newName := fmt.Sprintf("%s_%d", name, constSeen[name])
					line = strings.Replace(line, "\t"+name+"\t", "\t"+newName+"\t", 1)
					if !strings.Contains(line, "\t"+newName+"\t") {
						line = strings.Replace(line, "\t"+name+" ", "\t"+newName+" ", 1)
					}
				}
			}
			out = append(out, line)
			continue
		}

		// — Skip body of a Validate() method we decided to suppress —
		if skipBody {
			if line == "}" {
				skipBody = false
			}
			continue
		}

		// — Validate comment buffering —
		// When we see the "// Validate validates s …" comment, buffer it
		// in case the next non-blank line is a Validate() func for a
		// shadowed type. If so, we suppress both the comment and the func.
		if reValidateComment.MatchString(line) {
			pendingLines = append(pendingLines, line)
			continue
		}
		if len(pendingLines) > 0 {
			if m := reValidateFunc.FindStringSubmatch(line); m != nil {
				typeName := m[1]
				if shadowed[typeName] {
					// Suppress comment and start skipping the method body
					pendingLines = nil
					skipBody = true
					continue
				}
				// Not shadowed — emit the buffered comment and this line
				out = append(out, pendingLines...)
				pendingLines = nil
				out = append(out, line)
				continue
			}
			// Empty line or something else after the comment — emit buffered
			out = append(out, pendingLines...)
			pendingLines = nil
			out = append(out, line)
			continue
		}

		out = append(out, line)
	}

	if len(pendingLines) > 0 {
		out = append(out, pendingLines...)
	}

	return out
}
