// Code generated by cisco-vk-yang-sync. DO NOT EDIT.
//
// Blank-imports all per-family ygot schema packages for release 1715 so their
// init() functions fire and register with cfgvalidation. This activates ygot
// schema validation in the fixture harness for every family whose schema was
// successfully generated (skip-listed families are absent).

package writers

import (
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/aaa"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/banner"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/cdp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/class_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/clock"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/dhcp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/eigrp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/errdisable"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/interface_ethernet"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/interface_loopback"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/interface_port_channel"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/interface_switchport"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/interface_tunnel"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/interface_virtual_port_group"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/interface_vlan"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/ip_domain"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/ip_name_server"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/ip_ssh"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/ipv6_access_list_extended"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/ipv6_access_list_standard"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/ipv6_prefix_list"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/line"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/logging"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/ntp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/ospf"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/policy_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/prefix_list"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/route_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/snmp_server"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/spanning_tree"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/static_route"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/track"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/username"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/vlan"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1715/vrf"
)
