// Code generated by cisco-vk-yang-sync. DO NOT EDIT.
//
// Blank-imports all per-family ygot schema packages for release 1715 so their
// init() functions fire and register with cfgvalidation. This activates ygot
// schema validation in the fixture harness for every family whose schema was
// successfully generated (skip-listed families are absent).

package writers

import (
)
