// Code generated by cisco-vk-yang-sync. DO NOT EDIT.
//
// Blank-imports all per-family ygot schema packages for release 1718 so their
// init() functions fire and register with cfgvalidation. This activates ygot
// schema validation in the fixture harness for every family whose schema was
// successfully generated (skip-listed families are absent).

package writers

import (
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/aaa"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/banner"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/cdp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/class_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/clock"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/dhcp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/eigrp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/errdisable"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/interface_ethernet"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/interface_loopback"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/interface_port_channel"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/interface_switchport"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/interface_tunnel"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/interface_virtual_port_group"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/interface_vlan"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/ip_domain"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/ip_name_server"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/ip_ssh"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/ipv6_access_list_extended"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/ipv6_access_list_standard"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/ipv6_prefix_list"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/line"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/logging"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/ntp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/ospf"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/policy_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/prefix_list"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/route_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/snmp_server"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/spanning_tree"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/static_route"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/track"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/username"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/vlan"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/1718/vrf"
)
