// Code generated by cisco-vk-yang-sync. DO NOT EDIT.
//
// Blank-imports all per-family ygot schema packages for release 2601 so their
// init() functions fire and register with cfgvalidation. This activates ygot
// schema validation in the fixture harness for every family whose schema was
// successfully generated (skip-listed families are absent).

package writers

import (
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/aaa"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/banner"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/cdp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/class_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/clock"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/dhcp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/eigrp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/errdisable"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/interface_ethernet"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/interface_loopback"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/interface_port_channel"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/interface_switchport"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/interface_tunnel"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/interface_virtual_port_group"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/interface_vlan"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/ip_domain"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/ip_name_server"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/ip_ssh"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/ipv6_access_list_extended"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/ipv6_access_list_standard"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/ipv6_prefix_list"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/line"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/logging"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/ntp"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/ospf"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/policy_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/prefix_list"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/route_map"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/snmp_server"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/spanning_tree"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/static_route"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/track"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/username"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/vlan"
	_ "github.com/cisco/virtual-kubelet-cisco/internal/drivers/iosxe/configdriver/generated/2601/vrf"
)
