apiVersion: config.cisco.vk/v1alpha1
kind: IOSXEDiagnostic
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.cisco.vk/v1alpha1","kind":"IOSXEDiagnostic","metadata":{"annotations":{},"name":"t3-allow-secrets","namespace":"cisco-vk-smoke"},"spec":{"allowSecrets":true,"commands":["show running-config | include username"],"deviceRef":{"name":"cat9k-smoke"}}}
  creationTimestamp: "2026-04-28T06:48:22Z"
  generation: 1
  name: t3-allow-secrets
  namespace: cisco-vk-smoke
  resourceVersion: "370245"
  uid: bd182c3a-1aa3-4065-ae97-613f067d19d3
spec:
  allowSecrets: true
  commands:
  - show running-config | include username
  deviceRef:
    name: cat9k-smoke
status:
  conditions:
  - lastTransitionTime: "2026-04-28T06:48:23Z"
    message: 1 command(s) captured
    observedGeneration: 1
    reason: Captured
    status: "True"
    type: Ready
  lastCapture: "2026-04-28T06:48:22Z"
  observedGeneration: 1
  phase: Completed
  results:
  - capturedAt: "2026-04-28T06:48:22Z"
    commands:
    - command: show running-config | include username
      output: |-
        username cisco privilege 15 secret 9 ***REDACTED***
        username admin privilege 15 secret 9 ***REDACTED***
        username ***REDACTED-user*** privilege 15 secret 9 ***REDACTED***
        username ***REDACTED-user*** privilege 15 secret 9 ***REDACTED***
        ip ftp username cisco
